CC=/Applications/MATLAB_R2011b.app/bin/mex 
CXX=/Applications/MATLAB_R2011b.app/bin/mex 

all: tinv tcomp

tinv: tinv.cpp
	$(CXX) $(CXXFLAGS) -v -o $@ $<

tcomp: tcomp.cpp
	$(CXX) $(CXXFLAGS) -v -o $@ $<


