modifier = {};
modifier.type = 'random';
modifier.name = 'random';
modifier.maxMods = 2;
modifier.minMods = 0;
modifier.replace = false;
modifier.modifiers{1} = 'config/curve_modifiers/bounce.mat';
modifier.modifiers{2} = 'config/curve_modifiers/snake.mat';
save('config/curve_modifiers/random', '-struct', 'modifier');
