modifier = {};
modifier.type = 'sine';
modifier.name = 'snake';
modifier.sampleRate = 150;
modifier.amplitude  = 0.3;
modifier.period     = 2.0;
modifier.verShift   = 0;
modifier.horShift   = pi / 2;
modifier.direction  = [ 0; 1; 0 ];
save('config/curve_modifiers/snake', '-struct', 'modifier');
